-- 상위 n개 레코드
SELECT NAME 
FROM AMIMAL_INS 
ORDER BY DATETIME LIMIT 1;

-- 여러 기준으로 정렬하기 
SELECT ANIMAL_ID, NAME, DATETIME 
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC;

-- 동물 아이디와 이름
SELECt ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- 어린 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION NOT LIKE "Aged"
ORDER BY ANIMAL_ID;

-- 아픈 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS 
WHERE INTAKE_CONDITION = "Sick"
ORDER BY ANIMAL_ID;

-- 이름이 있는 동물의 아이디
SELECT ANIMAL_ID 
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

-- 역순 정렬하기
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

-- 이름이 없는 동물의 아이디
SELECT ANIMAL_ID 
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID;

-- 최댓값 구하기
SELECT MAX(DATETIME)
FROM ANIMAL_INS;

-- 모든 레코드 조회하기
SELECT * 
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;
